# Generated by Django 4.2.16 on 2024-11-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_provincia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_municipio', models.CharField(max_length=30)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amp.provincias')),
            ],
        ),
    ]
