# Generated by Django 4.2.16 on 2024-11-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipios',
            new_name='Municipio',
        ),
        migrations.RenameModel(
            old_name='Provincias',
            new_name='Provincia',
        ),
    ]
