# Generated by Django 4.2.16 on 2024-11-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0002_rename_municipios_municipio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
