# Generated by Django 4.2.16 on 2024-11-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0003_alter_municipio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
