# Generated by Django 4.2.16 on 2024-11-29 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0004_alter_provincia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=10)),
                ('house_street1', models.CharField(max_length=30)),
                ('house_street2', models.CharField(max_length=30)),
                ('house_street3', models.CharField(max_length=30)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amp.municipio')),
            ],
            options={
                'verbose_name': 'ClientAddress',
                'verbose_name_plural': 'ClientAddresss',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('alias_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(default='default@defaul.org', max_length=254)),
                ('client_age', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amp.clientaddress')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
