# Generated by Django 4.2.16 on 2024-11-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0005_clientaddress_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientAddress',
        ),
    ]
