# Generated by Django 4.2.16 on 2024-12-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0007_clientaddress_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscription_name', models.CharField(max_length=50)),
                ('suscription_cost', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAT', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SuscriptionType',
                'verbose_name_plural': 'SuscriptionTypes',
            },
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscription_status', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amp.client')),
                ('suscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amp.suscriptiontype')),
            ],
            options={
                'verbose_name': 'Suscription',
                'verbose_name_plural': 'Suscriptions',
            },
        ),
    ]
