# Generated by Django 4.2.16 on 2024-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0009_gamecategory_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='static/img/cardgb.jpeg', upload_to='static/img'),
        ),
    ]
